services:
  - type: web
    name: commandes-service
    env: custom
    buildCommand: ./mvnw clean package -DskipTests=true
    startCommand: java -jar target/ton-app.jar
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d2g011n5r7bs73efcml0-a.oregon-postgres.render.com:5432/commandes_nsp9
      - key: SPRING_DATASOURCE_USERNAME
        value: commandes_nsp9_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: jObPgLrtPLOh9aG4VwqWHK6HoKfUAj7k
      - key: PORT
        value: 8081  # Render injecte aussi un PORT env variable par défaut

previews:
  generation: automatic
  expireAfterDays: 365
