#execution Local
#spring.application.name=commandes

#server.port=${PORT:8081}
#app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/commandes}
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://neondb_owner:npg_nEZRStsGVo71@ep-blue-wind-asarzd7l-pooler.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

#spring.jpa.show-sql=${JPA_SHOW_SQL:false}
#spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
#spring.jpa.open-in-view=false

#spring.security.user.name=${APP_SECURITY_USER:user}
#spring.security.user.password=${APP_SECURITY_PASSWORD:********}

#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.enabled=true
#springdoc.api-docs.enabled=true


#EXECUTION SUR LA BD EN LIGNE SUPABASE
spring.application.name=commandes

server.port=${PORT:8081}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

# =========================================================
# SUPABASE
# =========================================================

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.zmmpqqrvjetcpqjfxyzg}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# =========================================================
# JPA
# =========================================================

spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false

# =========================================================
# SECURITY
# =========================================================

spring.security.user.name=${APP_SECURITY_USER:user}
spring.security.user.password=${APP_SECURITY_PASSWORD:12345678}

# =========================================================
# SWAGGER
# =========================================================

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true