spring.application.name=commandes

server.port=${PORT:8081}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/commandes}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false

spring.security.user.name=${APP_SECURITY_USER:user}
spring.security.user.password=${APP_SECURITY_PASSWORD:monmotdepasse}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
